### ISSUE TITLE
Error when building: The following glyph names are referenced but are missing from the glyph set: adotbelow

### ISSUE THREAD

**Issue by arkthur** [ofolis/consolig#9]
I don't know what I'm doing wrong. I think I followed your instructions to the letter, but when I run the `build.py`, it throws this error:
```
Setting up directories.
Processing UFO source at "D:\Downloads\consolig-master\consolig-master\sources\Consolig-Regular.ufo".
Converting UFO to TTF.
Merging TrueType data.
Dropped cmap subtable from font [0]:    format  6, platformID  1, platEncID  0
Writing TrueType features.
Traceback (most recent call last):
  File "build.py", line 122, in <module>
    addOpenTypeFeatures(merged_tt_font, feature_file_path)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\fontTools\feaLib\builder.py", line 21, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\fontTools\feaLib\builder.py", line 107, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\fontTools\feaLib\parser.py", line 69, in parse
    statements.append(self.parse_glyphclass_definition_())
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\fontTools\feaLib\parser.py", line 229, in parse_glyphclass_definition_
    glyphs = self.parse_glyphclass_(accept_glyphname=False)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\fontTools\feaLib\parser.py", line 317, in parse_glyphclass_
    self.check_glyph_name_in_glyph_set(glyph)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\fontTools\feaLib\parser.py", line 1539, in check_glyph_name_in_glyph_set
    raise FeatureLibError(
fontTools.feaLib.error.FeatureLibError: D:\Downloads\consolig-master\consolig-master\sources\features.fea:2:114: The following glyph names are referenced but are missing from the glyph set: adotbelow
```
I don't know if this is the best place to ask this kind of question. If not, I'm sorry.

**Comment by gsmeets** [comment]
Yeah, I'm getting the same issue on my windows 10 machine.

**Comment by ofolis** [comment]
Interesting. I'll try to reproduce this this weekend. Thanks for submitting this.

**Comment by arkthur** [comment]
Hi there, hoping everyone is fine and healthy. Any updates in this issue?

**Comment by ofolis** [comment]
Sorry for the delay, all. Thanks for the nudge. Let me genuinely give this a look tonight.

If I still don't make it happen, I'm taking off this next week from work, so I'll have much more time to fit in my side projects. 🙇‍♂️

**Comment by ofolis** [comment]
I have successfully been able to replicate this on my own Windows 10. I'll have more info soon.

**Comment by ofolis** [comment]
Got this one squashed. Looks like one of the deps got smarter about checking for glyphs I was claiming existed. Removed those from the declaration and it was happy.

https://github.com/ofolis/consolig/releases/tag/v0.4.0

**Comment by arkthur** [comment]
Just tested it and it worked perfectly. Thanks a lot ☺
